Added signature support for ECC
fmonteiro93/MoCOCrW pull request #3
Opened 2018-11-26 14:23 UTC by sz-ctw

2018-11-26 16:01 UTC, goncalogouveiacriticaltechworkscom requested changes
Please check my comments.
note: as requested, tests not reviewed.

2018-11-26 16:01 UTC, goncalogouveiacriticaltechworkscom commented on src/mococrw/signature.h
> +     * Creates an ECC signature for a plain text message based on a given private key.
[Sign vs. Creates]:
In the @brief section it is stated "Sign a message". Here we state that "Creates an ECC signature". IMO this is a little bit confusing. This method signs a message and returns a signed message? Or returns the signature for the given message?

2018-11-26 16:01 UTC, goncalogouveiacriticaltechworkscom commented on src/mococrw/signature.h
> +    static std::vector<uint8_t> create(AsymmetricPrivateKey &privateKey,
In this file, there are a lot of create methods, with distinct signatures. How does a user know that this method creates an ECC signature and not other type of signature? From the usability perspective, I consider this somehow confusing, and imposes that the user of this code needs to have a deep knowledge about cryptography in order to be able to effectively use the code. Please consider to review the concept behind the naming of these methods.

For instance, you can use namespaces to separate ECC, RSA, and so on, functionalities:
auto signedMessage = mococrw::ecc::create(...);
auto signedMessage = mococrw::rsa::create(...);

Or you can rename the methods:
auto signedMessage = mococrw::createECC(...);
auto signedMessage = mococrw::createRSA(...);

2018-11-26 16:01 UTC, goncalogouveiacriticaltechworkscom commented on src/mococrw/signature.h
> +                                        const std::string message);
Consider to user const std::string& instead.

2018-11-26 16:01 UTC, goncalogouveiacriticaltechworkscom commented on src/mococrw/signature.h
> +                                       const std::vector<uint8_t> messageDigest);
Consider user const std::vector& instead.

2018-11-26 16:01 UTC, goncalogouveiacriticaltechworkscom commented on src/mococrw/signature.h
> +                       const std::vector<uint8_t> signature,
Consider use const std::vector& instead.
Consider user const std::string& instead (next line).

2018-11-26 16:01 UTC, goncalogouveiacriticaltechworkscom commented on src/mococrw/signature.h
> +                       const std::vector<uint8_t> signature,
Consider use const std::vector& instead.
Consider user const std::string& instead (next line).

2018-11-26 16:01 UTC, goncalogouveiacriticaltechworkscom commented on src/mococrw/signature.h
> +                       const std::vector<uint8_t> signature,
Consider use const std::vector& instead.
Consider user const std::string& instead (next line).

2018-11-26 16:01 UTC, goncalogouveiacriticaltechworkscom commented on src/mococrw/signature.h
> +                       const std::vector<uint8_t> signature,
Consider use const std::vector& instead. The same applies for the next line.

2018-11-26 16:01 UTC, goncalogouveiacriticaltechworkscom commented on src/signature.cpp
> +        if (!keyCtx.get()) {
Consider put these 3 lines of code immediately after creating the context (after line 50). This way we create and immediately check the context.

2018-11-26 16:01 UTC, goncalogouveiacriticaltechworkscom commented on src/signature.cpp
> +    std::vector<uint8_t> signature;
nnot used. Please remove.

2018-11-26 16:01 UTC, goncalogouveiacriticaltechworkscom commented on src/signature.cpp
> +    messageDigest = digestMessage(message, digestType);
In line 36, we added a try-catch around this method. Here we didn't follow the same implementation. Please check if both are correct.

2018-11-26 16:01 UTC, goncalogouveiacriticaltechworkscom commented on src/signature.cpp
> +    const auto keyCtx = _EVP_PKEY_CTX_new(publicKey.internal());
Here we are not checking if we got a valid context. Please add the protection.

2018-11-28 14:47 UTC, sz-ctw commented on src/mococrw/signature.h
> +     * Creates an ECC signature for a plain text message based on a given private key.
Corrected.

2018-11-28 14:47 UTC, sz-ctw commented on src/mococrw/signature.h
> +                                        const std::string message);
Corrected.

2018-11-28 14:47 UTC, sz-ctw commented on src/mococrw/signature.h
> +                                       const std::vector<uint8_t> messageDigest);
Corrected.

2018-11-28 14:47 UTC, sz-ctw commented on src/mococrw/signature.h
> +                       const std::vector<uint8_t> signature,
Corrected.

2018-11-28 14:47 UTC, sz-ctw commented on src/mococrw/signature.h
> +                       const std::vector<uint8_t> signature,
Corrected.

2018-11-28 14:47 UTC, sz-ctw commented on src/mococrw/signature.h
> +                       const std::vector<uint8_t> signature,
Corrected.

2018-11-28 14:47 UTC, sz-ctw commented on src/mococrw/signature.h
> +                       const std::vector<uint8_t> signature,
Corrected.

2018-11-28 14:47 UTC, sz-ctw commented on src/signature.cpp
> +    std::vector<uint8_t> signature;
Done.

2018-11-28 14:47 UTC, sz-ctw commented on src/signature.cpp
> +        if (!keyCtx.get()) {
Done.

2018-11-28 14:47 UTC, sz-ctw commented on src/signature.cpp
> +    messageDigest = digestMessage(message, digestType);
Harmonized. Added try/catch block

2018-11-28 14:47 UTC, sz-ctw commented on src/signature.cpp
> +    const auto keyCtx = _EVP_PKEY_CTX_new(publicKey.internal());
Updated, moved inside "try" block. EVP_PKEY_CTX_new can throw OpenSSL exception if the pointer is null.

2018-11-28 16:12 UTC, pmvfonseca requested changes
Nice job! I like the new class structure, it's more elegant than before.

2018-11-28 16:12 UTC, pmvfonseca commented on src/mococrw/signature.h
> +private:
Minor nitpick: I think we should switch the order of the private and public methods. It increases class readability IMO.

2018-11-28 16:12 UTC, pmvfonseca commented on src/mococrw/signature.h
> +         * Verifies a signature based on the signed message and a given public key and padding mode.
AFAIK when signing with ECC there is no padding :)

2018-11-28 16:12 UTC, pmvfonseca commented on src/mococrw/signature.h
> +         * Verifies a signature based on the message digest and a given public key and padding mode.
See comment above.

2018-11-28 16:12 UTC, pmvfonseca commented on src/mococrw/signature.h
> +     * Returns the signed message in @signedMessage
Doesn't it return only the signature itself?

2018-11-28 16:12 UTC, pmvfonseca commented on src/mococrw/signature.h
> +     * Propagates the OpenSSLException in case of failure.
Does this comment also apply on the method above?

2018-11-28 16:12 UTC, pmvfonseca commented on src/signature.cpp
> +    if (operation == OperationType::Sign) {
A conditional/ternary operator would look cooler here :smirk:

2018-11-28 16:12 UTC, pmvfonseca commented on src/signature.cpp
> +    if (operation == OperationType::Sign) {
See above

2018-11-28 16:12 UTC, pmvfonseca commented on src/signature.cpp
> +        messageDigest = digestMessage(message,  DigestTypes::SHA1);
Why is only SHA1 supported at the moment? It is considered to be insecure. Shouldn't the user have the option to choose the digest algorithm?

Furthermore, if SHA1 remains as the only supported algorithm then the documentation should emphasize this.

2018-11-28 16:12 UTC, pmvfonseca commented on src/signature.cpp
> +
Remove the extra line :)

2018-11-28 16:12 UTC, pmvfonseca commented on tests/unit/test_signature.cpp
> +    static const std::string _validEccPublicKey;
Maybe we should add a small comment with the information of what curve was chosen to generate the keys.

2018-11-28 16:12 UTC, pmvfonseca commented on tests/unit/test_signature.cpp
> +    std::unique_ptr<AsymmetricKeypair> _keyPairRsa;
Small nitpick that applies to the whole file: I think RSA and ECC should always be fully capitalized.

2018-11-28 16:25 UTC, goncalogouveiacriticaltechworkscom requested changes
Nice work!
Just check my review comment.

2018-11-28 16:25 UTC, goncalogouveiacriticaltechworkscom commented on tests/unit/test_signature.cpp
> +}
Missing new line

2018-11-28 16:28 UTC, goncalogouveiacriticaltechworkscom commented on tests/unit/test_signature.cpp
> +    std::unique_ptr<AsymmetricKeypair> _keyPairRsa;
I think code conventions state to just capitalize the first letter.

2018-11-28 16:29 UTC, goncalogouveiacriticaltechworkscom commented on src/signature.cpp
> +    if (operation == OperationType::Sign) {
I prefer the way it is implemented :)

2018-11-28 17:04 UTC, joaoferreira-ctw commented on src/mococrw/signature.h
> +private:
Agreed. Changed as suggested.

2018-11-28 17:04 UTC, joaoferreira-ctw commented on src/mococrw/signature.h
> +     * Returns the signed message in @signedMessage
Yes it does...

2018-11-28 17:04 UTC, joaoferreira-ctw commented on src/mococrw/signature.h
> +     * Propagates the OpenSSLException in case of failure.
Agree. Added info to the previous method.

2018-11-28 17:04 UTC, joaoferreira-ctw commented on src/mococrw/signature.h
> +         * Verifies a signature based on the signed message and a given public key and padding mode.
Corrected.

2018-11-28 17:04 UTC, joaoferreira-ctw commented on src/mococrw/signature.h
> +         * Verifies a signature based on the message digest and a given public key and padding mode.
Corrected.

2018-11-28 17:04 UTC, joaoferreira-ctw commented on src/signature.cpp
> +    if (operation == OperationType::Sign) {
Looking cool indeed!

2018-11-28 17:04 UTC, joaoferreira-ctw commented on src/signature.cpp
> +    if (operation == OperationType::Sign) {
Corrected.

2018-11-28 17:04 UTC, joaoferreira-ctw commented on src/signature.cpp
> +
Removed.

2018-11-28 17:04 UTC, joaoferreira-ctw commented on src/signature.cpp
> +        messageDigest = digestMessage(message,  DigestTypes::SHA1);
OpenSSL documentation claims to support SHA1 exclusively, but SHA256 and SHA512 also work as confirmed by unit tests. Added support for SHA256 and SHA512.

2018-11-28 17:27 UTC, joaoferreira-ctw commented on tests/unit/test_signature.cpp
> +    std::unique_ptr<AsymmetricKeypair> _keyPairRsa;
Agree. Rejected first comment.

2018-11-28 17:27 UTC, joaoferreira-ctw commented on tests/unit/test_signature.cpp
> +    static const std::string _validEccPublicKey;
Agreed. Added.

2018-11-28 17:27 UTC, joaoferreira-ctw commented on tests/unit/test_signature.cpp
> +}
![Alt Text](https://media3.giphy.com/media/Vns2DRR16K9q0/giphy.gif)

2018-11-28 17:40 UTC, goncalogouveiacriticaltechworkscom approved these changes
Looks good to me.

2018-11-28 17:41 UTC, pmvfonseca approved these changes

2018-11-28 17:41 UTC, pmvfonseca commented on tests/unit/test_signature.cpp
> +    std::unique_ptr<AsymmetricKeypair> _keyPairRsa;
![](https://media0.giphy.com/media/5hkCGzg4jjQcEXQ6R9/giphy.gif)

2018-11-29 10:02 UTC, merged